### ISSUE TITLE
GTK crashes

### ISSUE THREAD

**Issue by VladislavAntonyuk** [jsuarezruiz/xamarin-forms-gtk-weather-sample#1]
GTK application closes on line Gtk.Application.Run() with exit code 1. Error in ExceptionManager.

I have tried to comment this line. So FormWindow appears but then closes, with the same error.

**Comment by jsuarezruiz** [comment]
Are you trying in Windows, macOS or Linux?, can you share more info (Xamarin.Forms version, etc)?

**Comment by VladislavAntonyuk** [comment]
I am using Windows 10 1803, XF used 3.0 and later, GTK 2.12.0.0

I cloned this repository (changed .net framework to 4.7.2). Run GTK project. The Window appears and immidiately closes.

**Comment by VladislavAntonyuk** [comment]
The problem is solved by installing GTK# for .NET (not only Mono)
